src/country/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.models import User
from lespays.views import Classeviewset,Eleveviewset
from rest_framework import routers
from lespays.models import Classe,Eleve

router = routers.DefaultRouter()
router.register('Classe', Classeviewset)
router.register('Eleve', Eleveviewset)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lespays.urls')),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(router.urls)),
]

src/lespays/urls.py
from django.urls import path
from lespays import views
urlpatterns = [
    path('', views.accueil, name='accueil'),
    path('ajouter_classe/', views.ajouter_classe, name='ajouter_classe'),
    path('ajouter_eleve/<int:classe_id>/', views.ajouter_eleve, name='ajouter_eleve'),
    path('detail_classe/<int:classe_id>/', views.detail_classe, name='detail_classe'),
    path('supprimer_classe/<int:classe_id>/', views.supprimer_classe, name='supprimer_classe'),
    path('supprimer_eleve/<int:eleve_id>/', views.supprimer_eleve, name='supprimer_eleve'),
]

src/lespays/models.py
from django.db import models

class Classe(models.Model):
    nom = models.CharField(max_length=100, default="aucun")
    specialite = models.CharField(max_length=100, default="aucun")

class Eleve(models.Model):
    nom = models.CharField(max_length=100, default="aucun")
    lieu_de_naissance = models.CharField(max_length=100, default="aucun")
    date_de_naissance = models.CharField(max_length=100, default="aucun")
    classe = models.ForeignKey(Classe, on_delete=models.CASCADE)

src/lespays/forms.py
from django import forms
from .models import Classe, Eleve

class FormClasse(forms.ModelForm):
    class Meta:
        model = Classe
        fields = ['nom','specialite']
        widgets = {
            'nom': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),
            'specialite': forms.TextInput(attrs={'class': 'form-control form-control-lg'}) 
        }

class FormEleve(forms.ModelForm):
    class Meta:
        model = Eleve
        fields = ['nom', 'lieu_de_naissance', 'date_de_naissance']
        widgets = {
            'nom': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),  # Ajouter la classe 'form-control-lg' de Bootstrap
            'lieu_de_naissance': forms.TextInput(attrs={'class': 'form-control form-control-lg'}),  # Ajouter la classe 'form-control-lg' de Bootstrap
            'date_de_naissance': forms.NumberInput(attrs={'class': 'form-control'})  # Conserver la classe 'form-control' de Bootstrap
        }

src/lespays/views.py
from django.shortcuts import render, redirect
from .models import Classe, Eleve
from .forms import FormClasse, FormEleve

from .serializer import ClasseSerializer, EleveSerializer
from rest_framework import viewsets

def accueil(request):
    classes = Classe.objects.all()
    return render(request, 'accueil.html', {'classes': classes})

def ajouter_classe(request):
    if request.method == 'POST':
        form = FormClasse(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accueil')
    else:
        form = FormClasse()
    return render(request, 'ajouter_classe.html', {'form': form})

def ajouter_eleve(request, classe_id):
    classe = Classe.objects.get(pk=classe_id)
    if request.method == 'POST':
        form = FormEleve(request.POST)
        if form.is_valid():
            eleve = form.save(commit=False)
            eleve.classe = classe
            eleve.save()
            # Redirection vers la page de détail du classe
            return redirect('detail_classe', classe_id=classe_id)
    else:
        form = FormEleve()
    return render(request, 'ajouter_eleve.html', {'form': form, 'classe': classe})
    
def detail_classe(request, classe_id):
    classe = Classe.objects.get(pk=classe_id)
    eleve = Eleve.objects.filter(classe=classe)
    return render(request, 'detail_classe.html', {'classe': classe, 'eleve': eleve})

    
def supprimer_classe(request, classe_id):
    classe = Classe.objects.get(pk=classe_id)
    classe.delete()
    return redirect('accueil')

def supprimer_eleve(request, eleve_id):
    eleve = Eleve.objects.get(pk=eleve_id)
    classe_id = eleve.classe.id
    eleve.delete()
    return redirect('detail_classe', classe_id=classe_id)

    
class Classeviewset(viewsets.ModelViewSet):
   
    queryset = Classe.objects.all()
    serializer_class = ClasseSerializer

class Eleveviewset(viewsets.ModelViewSet):
    
    queryset = Eleve.objects.all()
    serializer_class = EleveSerializer

src/lespays/templates/accueil.html
<!DOCTYPE html>
<html>
<head>
    <title>Classes</title>
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container-fluid w100" style="margin-top: 70px;">
        <h1 class="mt-5 text-center">Classes</h1>
        <ul style="box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1); margin-bottom: 50px;" class="list-group mt-3">
            {% for classe in classes %}
            <li class="list-group-item"><strong><a href="{% url 'detail_classe' classe.id %}">{{ classe.nom }}</a></strong></li>
            <p>{{ classe.specialite }}</p>
            {% endfor %}
        </ul>
        <a href="{% url 'ajouter_classe' %}" class="btn btn-primary mt-3 w-100">Ajouter un classe</a>
        
    </div>
    {% for classe in classes %}
    <ul class="list-group">
        <li class="list-group-item">
            {{ classe.nom }}
            <a href="{% url 'supprimer_classe' classe.id %}">Supprimer</a>
        </li>
    </ul>
   
    {% endfor %}
    <script src="../static/js/all.js"></script>
</body>
</html>

src/lespays/templates/ajouter_continent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <title>Ajouter un classe</title>
</head>
<body>
    <div style="box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);" class="container mt-5">
        <div style="margin-top: 150px;" class="row">
            <div style="border-top: 100px; padding-top: 20px; padding-bottom: 20px;" class="col-12">
                <h3 class="mb-4">Ajouter un classe</h3>
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <strong>{{ form.as_p }}</strong>
                    </div>
                    <button type="submit" class="btn btn-primary mt-3 w-100">Soumettre</button> 
                </form>
            </div>
        </div>
    </div>
    <script src="../static/js/all.js"></script>
</body>
</html>

src/lespays/templates/ajouter_pays.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <title>Ajouter un eleve</title>
    
</head>
<body>
    <div  class="container-fluid w100">
        <div  class="row justify-content-center">
            <div style="box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1); margin-top: 100px;" class="col-md-6">
                <h3 class="mb-4">Ajouter un eleve</h3>
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                       <strong>{{ form.as_p }}</strong> 
                    </div>
                    <button type="submit" class="btn btn-primary mt-3 w-100">Soumettre</button>
                    
                </form>
            </div>
        </div>
    </div>
    <script src="../static/js/all.js"></script>
</body>
</html>

src/lespays/templates/detail_continent.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Détail du Classe {{ classe.nom }}</title>
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f8f9fa;
        }
    </style>
</head>
<body>
    <div  class="container py-5">
        <div  class="row">
            <div  class="container-fluid w25" >
                <div class="container-fluid w25"  style=" padding-top: 50px; padding-bottom: 50px; box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);" class="card">
                    <div class="container-fluid w25" >
                        <h2 class="card-title text-center mb-4">DETAILS DE LA CLASSE</h2>
                        <p class="card-text"><strong>&nbsp&nbsp{{ classe.nom }}</strong></p>
                        <h3 class="mt-4">ELEVES DANS CET CLASSE </h3>
                        <ul class="list-group">
                            {% for eleve in eleve %}
                            <li class="list-group-item">
                                <div class="row">
                                    <div class="container-fluid w25" >
                                        <p><strong>Nom<font color="#0d6efd"> {{ eleve.nom }}</font> </strong></p>
                                        <p><strong>Lieu_de_naissance<font color="#0d6efd"> {{ eleve.lieu_de_naissance }} </strong> </font> </p>
                                        <p><strong>Date_de_naissance<font color="#0d6efd"> {{ eleve.date_de_naissance }} </strong> </font> </p>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                        <a href="{% url 'ajouter_eleve' classe.id %}" class="btn btn-primary mt-3 w-100">Ajouter un eleve</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
  
  <div style="border-top: 100px;">
    <ul class="list-group">
        {% for eleve in classe.eleve_set.all %}
            <li class="list-group-item">
                {{ eleve.nom }}
                <font color="orange"> <a href="{% url 'supprimer_eleve' eleve.id %}">Supprimer</a></font>
            </li>
        </ul>
  </div>
   
   
    {% endfor %}
    <script src="../static/js/all.js"></script>
</body>
</html>